#!/bin/bash -e

cd "$(dirname "$0")"
source scripts/_common.sh

checkBinary docker
checkBinary docker-compose
checkComposer

clean
buildDir

buildGuzzle
buildDnsInstances
buildEnvironments
buildOtherServices

set +e

for env in `ls build/env`; do
    for test in `ls tests`; do
        outFile=build/out/${env}_${test}.out
        echo "Running test: ${test} on ${env} (> ${outFile})" >&2

        (
            command="cd /usr/src/tests/${test}; chmod +x run.sh; sync; ./run.sh"
            docker-compose run --rm "${env}" \
                '/bin/bash' -c "${command}" > ${outFile} 2>&1
        ) &

        sync
        sleep 1
    done
done

echo "Waiting for tests to complete..." >&2
wait

echo "All done" >&2
